### ISSUE TITLE
What is the appropriate way to request `[form]_complete` fields

### ISSUE THREAD

**Issue by nutterb** [nutterb/redcapAPI#107]
Following up on #106 I'd like to layout some thoughts on how to extract `[form]_complete` fields from a REDCap project.  Comments from @SophiaJia @januz @afleishman @wibeasley and others are welcome.

### Current Behavior

* `[form]_complete` fields are automatically included whenever any one field is included from the form.
* The user need not do anything to trigger the export of the `[form]_complete` field.
* The user has no way to explicitly request a `[form]_complete` field.

### Potential behaviors

**Require the user to explicitly request `[form]_complete` fields**

* Advantage: users gain full control over the export, with no implicit additions.  
* Disadvantage: breaks backward compatibility  
* Disadvantage: new or casual users may not know that the `[form]_complete` fields are available; may not know to request them (let's face it--most people don't read documentation)

**Always export `[form]_complete` fields**

* Advantage: These fields are always available.  
* Disadvantage: These fields aren't always useful.  
* Disadvantage: It adds a lot of implicitly exported fields for forms that may not be involved in the export.

**Add `[form]_complete` fields to the field names check**

* Advantage: Permits users to explicitly request a `[form]_complete` field.
* Advantage: Doesn't require requesting a field from the form to get a `[form]_complete field, which may permit cleaner exports.
* Advantage: Maintains existing behavior--no backward compatibility problems
* Disadvantage: Persists a behavior with implicit exports.

**Add `[form]_complete` fields to the field names check _and_ an option to turn off implicit export**

* Advantage: permits of the advantages of the previous option
* Advantage: allows users to turn off implicit export. Probably not a big performance concern, but for complex exports, it might be shave a little bit of time.
* Disadvantage: yet another argument

Looking over these options, each of the first three are pretty easy to implement.  The lasts option probably isn't too difficult either.  Any thoughts, preferences, or additions?

**Comment by januz** [comment]
My preference would be option 1 or 4, because they give the user explicit control over what columns will end up in the resulting data frame. As 1 is problematic regarding backward compatibility, 4 would be my favorite solution. Thank you very much for taking this on!

**Comment by nutterb** [comment]
Option 4 is implemented.  Please test with `devtools::install_github("nutterb/redcapAPI", ref = "devel")`  

Note the new option `form_complete_auto` which allows you to toggle on or off whether form complete fields are automatically included.  You may now also explicitly request form complete fields.

**Comment by januz** [comment]
works like a charm. Thanks a lot!!

**Comment by nutterb** [comment]
Thanks for working with me on this.
