### ISSUE TITLE
exportMetaData error

### ISSUE THREAD

**Issue by ldnicolasmay** [nutterb/redcapAPI#108]
Calling `exportReports` on a sandbox project, I get the following error from `exportMetaData`:

```
Error in if (meta_data$field_type[meta_data$field_name %in% x] == "checkbox") { : 
  argument is of length zero
``` 

I've looked through both `exportReports.R` and `exportMetaData.R` (the latter against an `data.frame` object returned from `exportMetaData`) but can't seem to identify why I'm getting this error. 

Any help would be appreciated. Thanks much!

**Comment by nutterb** [comment]
I think this is occurring in [`checkbox_suffixes`](https://github.com/nutterb/redcapAPI/blob/master/R/exportReports.R#L158-L160).  

Could you try two things for me and let me know what happens

1. Run `exportReports` with `labels = FALSE` (this should skip the problematic code)
2. Run `exportRecords` with `labels = TRUE` (I want to know if this affects the the Records export as well as the Reports)

If either of those fails, please send a copy of your meta data file to benjamin.nutter@gmail.com.

**Comment by ldnicolasmay** [comment]
`exportReports(..., labels = FALSE)` does indeed work.
`exportReports(... labels = TRUE)` throws the same error:

```
Error in if (meta_data$field_type[meta_data$field_name %in% x] == "checkbox") { : 
  argument is of length zero
```

I'll be emailing the metadata file shortly. Thank you!

**Comment by nutterb** [comment]
Think I got it.  I'm guessing you have `[form]_complete` fields in your report. These don't appear in the meta data and were causing the error.  I've added a line to account for these.  

Please try reinstalling with `devtools::install_github("nutterb/redcapAPI", ref = "devel")`

**Comment by ldnicolasmay** [comment]
Yep, this fixed it. Thank you!

**Comment by nutterb** [comment]
Glad that it worked.  Happy REDCapping!
