### ISSUE TITLE
importRecords throws error when there is no given minimum or maximum for the date fields?

### ISSUE THREAD

**Issue by mmagoo6** [nutterb/redcapAPI#109]
Hi,

I have a project that uses importRecords to update a redcap database, including several date entries. We are not concerned about forcing these entries to be above or below a certain level, so the data dictionary entries for "Text Validation Min" and "Text Validation Max" are blank. When I go to import the records, I get the following error. 
```
REDCap Data Import Log: 2018-03-06 22:56:26
The following (if any) conditions were noted about the data.
Error in as.POSIXct.numeric(field_min) : 'origin' must be supplied
```
I'm reasonably certain this comes from lines 44 and 53 of the [validateImport_methods.R](https://github.com/nutterb/redcapAPI/blob/09f847c94c83972d827fc29b860342b5123fabe6/R/validateImport_methods.R) sub-routine, and changing 
` w_low <- which(x < as.POSIXct(field_min))`
to
` w_low <- which(x < as.POSIXct(field_min,origin=origin))`
would work for my testcase.

For some background, I am taking over the responsibility of updating the redcap from a colleague of mine who had redcapAPI version 1.3 installed, and she was able to do the updates without an issue.

Thank you for looking at it

**Comment by nutterb** [comment]
I've been looking at this today and am somewhat surprised to see that error.  it doesn't make much sense that `as.POSIXct.numeric` would get called, since `field_min` should be a character string.  Would you be willing to share your meta data by e-mailing it to benjamin.nutter@gmail.com?

**Comment by mmagoo6** [comment]
I'd be happy to. What metadata specifically are you looking for?

**Comment by nutterb** [comment]
Ideally, whatever metadata file is in the project that generated the error.  I've not been able to replicate it on my system, so I want to inspect what might be unique about your configuration to cause the error.

**Comment by mmagoo6** [comment]
Sorry, my question was more elementary-what data do you need to recreate the error. I sent you an email with a dataset and code that is a mwe of the error I got. Please let me know if that's enough.

**Comment by nutterb** [comment]
Oh, I think I got it!  Please run

`devtools::install_github("nutterb/redcapAPI", ref = "devel")``

Let me know if the problem persists.

**Comment by mmagoo6** [comment]
Hi,


Thanks, but I still get the same error (using the same MWE that I sent)

> devtools::install_github("nutterb/redcapAPI", ref = "devel")
Downloading GitHub repo nutterb/redcapAPI@devel
from URL https://api.github.com/repos/nutterb/redcapAPI/zipball/devel
Installing redcapAPI
...
* installing *source* package 'redcapAPI' ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (redcapAPI)
Reloading installed redcapAPI
> packageVersion("redcapAPI")
[1] ‘2.0.2’
> library(redcapAPI)
>  rdin=read.csv("mwe.csv")
>  rdin$randomdate=as.Date(rdin$randomdate)
>  api=
>  rc.token=
>  rc.api=redcapConnection(url=api,token=rc.token)
>  importRecords(rc.api,rdin,returndata=T)
REDCap Data Import Log: 2018-04-10 21:42:29
The following (if any) conditions were noted about the data.

Error in as.POSIXct.numeric(field_min) : 'origin' must be supplied

________________________________

**Comment by nutterb** [comment]
How peculiar.  My results below.  I'm hoping it's as simple as I forgot to sync last night when I updated the code.

```r
> devtools::install_github("nutterb/redcapAPI", ref = "devel")
Downloading GitHub repo nutterb/redcapAPI@devel
from URL https://api.github.com/repos/nutterb/redcapAPI/zipball/devel
Installing redcapAPI
"C:/PROGRA~1/R/R-34~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  "C:/Users/Nutter/AppData/Local/Temp/RtmpuwqJAd/devtools3d03f5f5a3c/nutterb-redcapAPI-769d998"  \
  --library="C:/Users/Nutter/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'redcapAPI' ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (redcapAPI)
> packageVersion("redcapAPI")
[1] ‘2.0.3’
> library(redcapAPI)
> rcon <- redcapConnection(url = "",
+                          token = "")
> Import <- read.csv("mwe.csv")
> Import$randomdate <- as.Date(Import$randomdate)
> importRecords(rcon, Import, returnData = TRUE)
REDCap Data Import Log: 2018-04-11 20:55:14
The following (if any) conditions were noted about the data.


   record_id randomdate
1  821385237 1964-11-21
2  110590008 1989-02-13
3  371422447 1995-12-23
4  129013902 1996-09-17
5  992765192 1954-11-10
6  829341901 1939-03-07
7  129927549 1981-01-28
8  425138255 1936-10-24
9  123279866 1946-08-06
10 220499643 1998-09-22
11 459483189 1953-05-30
12 682840205 1971-06-03
13 411635723 1964-08-07
14 299583103 1959-12-26
15 258272496 1951-03-01
16 224699190 1983-06-19
17 971871662 1933-08-06
18 919184837 1951-09-20
19 621042526 1961-01-12
20 169080412 1981-05-17
> exportRecords(rcon)
   record_id randomdate demographics_complete
1  110590008 1989-02-13            Incomplete
2  123279866 1946-08-06            Incomplete
3  129013902 1996-09-17            Incomplete
4  129927549 1981-01-28            Incomplete
5  169080412 1981-05-17            Incomplete
6  220499643 1998-09-22            Incomplete
7  224699190 1983-06-19            Incomplete
8  258272496 1951-03-01            Incomplete
9  299583103 1959-12-26            Incomplete
10 371422447 1995-12-23            Incomplete
11 411635723 1964-08-07            Incomplete
12 425138255 1936-10-24            Incomplete
13 459483189 1953-05-30            Incomplete
14 621042526 1961-01-12            Incomplete
15 682840205 1971-06-03            Incomplete
16 821385237 1964-11-21            Incomplete
17 829341901 1939-03-07            Incomplete
18 919184837 1951-09-20            Incomplete
19 971871662 1933-08-06            Incomplete
20 992765192 1954-11-10            Incomplete
```

**Comment by nutterb** [comment]
The thing that confuses me the most though is

```r
Error in as.POSIXct.numeric(field_min) : 'origin' must be supplied
```

I can't fathom how a numeric value is getting into that comparison.  It seems like a malformed data dictionary.  I've added an origin argument to address this, but not knowing how a numeric is getting in there, I think we may find it circumvents the error but produces a lot of false flags on the validation.

**Comment by mmagoo6** [comment]
It's possible that it's the data dictionary. Here's a screenshot of the online editor though-it seems to say the same (pretty normal?) think that the text data dictionary was saying. Do you think it would be helpful for me to try and re-load the R package again?


________________________________

**Comment by nutterb** [comment]
This issue isn't present in the current version.
