### ISSUE TITLE
transfer of alerts from one project to another?

### ISSUE THREAD

**Issue by CarmenAHS** [nutterb/redcapAPI#11]
Hi I'm getting an invalid sender error when I'm uploading the alerts & Notifications from one project to another. My email address is valid, and user permissions are the same across both projects. Any suggestions?

**Comment by nutterb** [comment]
I am sorry I was  unable to provide assistance. This is a feature of REDCap I am unfamiliar with and is outside the scope of this package. Your REDCap Administrator or REDCap Community is likely your best resource.
