### ISSUE TITLE
bug in check_var in importRecords

### ISSUE THREAD

**Issue by mikestoller** [nutterb/redcapAPI#110]
checkbox variables are not assembled correctly. as a consequence, checkbox variables are rejected when trying to import them. There seems to be an error in the .opts on lines 169-172.

  .opts <- lapply(X = .opts, 
                  FUN = function(x) gsub(pattern = ",[[:print:]]+", 
                                         replacement = "", 
x = x))

**Comment by nutterb** [comment]
This has now been fixed. Use devtools::install_github("nutterb/redcapAPI", ref = "devel") to get the latest updates.

Thanks
