### ISSUE TITLE
Error when exporting reports

### ISSUE THREAD

**Issue by rittman** [nutterb/redcapAPI#112]
Hi,

I've just installed the library in R and can export records. When I try to export a report I get the error:

Error in if (meta_data$field_type[meta_data$field_name %in% x] == "checkbox") { : 
  argument is of length zero

I'm not quite sure what this means. Any help is appreciated.

Kind regards,

Tim

**Comment by nutterb** [comment]
It's possible that this is similar to #108 

A for that has been committed, but hasn't made it to CRAN  yet.  Could you try `devtools::install_github("nutterb/redcapAPI", ref = "devel")` and let me know if that solves the problem?

If not, I actually plan to work on debugging a few issues today, so hopefully you'll have something by the end of the weekend.

**Comment by rittman** [comment]
Thanks for the lightning fast response! I can confirm this solves the issue.

All the best,

Tim

**Comment by nutterb** [comment]
Great news.  Thanks for the report.
