### ISSUE TITLE
Error in as.character.factor(x) : malformed factor

### ISSUE THREAD

**Issue by MingBeres4d** [nutterb/redcapAPI#122]
Hello! 
I'm using this package to export data from one project into R, filter the data according to certain condition, remove missing data and then re-import the changed data to another project. 

I use "!is.na()" to remove the missing data. When all the variables' filed_type is text (like first_name, last_name), the code works just fun. But if I include any variables' filed_type is not text, like radio, dropdown, when I trying to print the changed data.frame, R will give me error: 
"Error in as.character.factor(x) : malformed factor
In addition: Warning message: In str.default(obj, ...) : 'object' does not have valid levels()" 
Is there anyway to fix this error? 
Thank you very much!

**Comment by nutterb** [comment]
This could be a tough one to replicate and isolate.  Let's start with some low-hanging fruit.  Can you send me the output of the following?

```r
R.Version()$version.string
packageVersion("redcapAPI")
```
The exact code you are using from when you start filtering our data would be helpful as well.  This will help me at least follow a similar workflow to try and recreate the issue.

Thanks

**Comment by MingBeres4d** [comment]
Thank you for the reply!
The following is the output of the R.Version, and packageVersion: 
> R.Version()$version.string
[1] "R version 3.5.0 (2018-04-23)"
Warning messages:
1: In str.default(obj, ...) : 'object' does not have valid levels()
2: In str.default(obj, ...) : 'object' does not have valid levels()
3: In str.default(obj, ...) : 'object' does not have valid levels()
> packageVersion("redcapAPI")
[1] ‘2.1.1’

My code: 
`demo=exportRecords(rcon_ex,events = "event_1_arm_1", factors = TRUE, forms = "demographics", checkboxLabels = FALSE)`
`demo1 = demo[,c("study_id","first_name","last_name", "sex", "dob", "race" )]`
`demo2 = demo1[demo1$race == "XXX" & !is.na(demo1$race), c(c("study_id","first_name","last_name", "dob", "sex"))]`

I can print out 'demo1'. I can also print out demo2 if the code is: 
`demo2 = demo1[demo1$race == "XXX" & !is.na(demo1$race), c(c("study_id","first_name","last_name", "dob"))]`
In my case, "sex" refer to gender, and the field_type is radio, "race" field_type is dropdown.

**Comment by nutterb** [comment]
I haven't been able to reproduce this yet, but I'm also running on one of the 3.4 versions of R.  I'm having trouble getting to 3.5 on linux, so I will have to work on this tomorrow when I can work on my Windows machine.

**Comment by nutterb** [comment]
It looks like the problem was related to the `labelVector` package.  If you don't mind, could you run

```
devtools::install_github("nutterb/labelVector")
devtools::install_github("nutterb/redcapAPI", ref = "devel")
```

and try your code again.  If that works, I'll get both packages update on CRAN in the next week.

**Comment by MingBeres4d** [comment]
My code works after I installed those packages! Thank you very much!

**Comment by nutterb** [comment]
Version 2.2 is now on CRAN.
