### ISSUE TITLE
`exportMetaData` not working with specific project

### ISSUE THREAD

**Issue by januz** [nutterb/redcapAPI#125]
running `exportMetaData()` results in 

```
[1] NA.
<0 rows> (or 0-length row.names)
```

for one of my projects. As a result, I also cannot use `importRecords()` as the field check fails. 

I wonder whether the issue is related to special characters (field labels are in German) or some formatting in the data dictionary of this project. It would be great if you could take a look (data dictionary attached) and tell me if you find something or have another idea what is going wrong. Thank you!

[data_dictionary.csv.zip](https://github.com/nutterb/redcapAPI/files/2420900/data_dictionary.csv.zip)

**Comment by nutterb** [comment]
Could you run `packageVersion("redcapAPI")` and let me know what version you're using?

I feel like I've tackled this before (perhaps in Issue #99). Just want to make sure I'm not trying to solve something I've solved before.

**Comment by januz** [comment]
I tried with versions `1.3` and `2.2`. The result is identical. Thanks!

**Comment by nutterb** [comment]
This won't be a final fix to get `importRecords` working, but if it works the way I hope, I'll be able to make up a quick patch for you.

Are you able to download the meta data with `exportMetaData(rcon, drop_utf8 = TRUE)`?

**Comment by januz** [comment]
hmm, no. That gives the same result. So maybe it's not related to special characters?!

**Comment by nutterb** [comment]
Certainly looks that way.  I'll try to look into it in the next couple of days.  Thanks for doing some of those diagnostics.

**Comment by januz** [comment]
I just did a further test: The problem is definitively related to the field labels. When I delete them and import the data dictionary to REDCap, the export works. I'll try to narrow it down further (e.g., deleting only labels that contain umlauts). Will let you know if I find something.

Thank you for your help!

**Comment by nutterb** [comment]
If you want to try something on the extreme side, you could process your data with `cleanseMetaData` and reload it to the project. But if you do, please do this in a copy of the project.

**Comment by januz** [comment]
I found the offending labels! Somehow REDCap changed some umlauts to non-UTF characters. After reverting them back to UTF-umlauts, the export works! Sorry to have bothered you with this, I should've checked the data dictionary more carefully first... Thank you!
