### ISSUE TITLE
Error in meta_data$field_name : $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by grauzerj** [nutterb/redcapAPI#126]
Hello!

When trying to pull data from REDCap into R using the exportRecords function, I receive the following error:

![image](https://user-images.githubusercontent.com/44295272/47220836-778bff80-d378-11e8-82f0-5bd9ad1dd006.png)

I use this function to export data from other REDCap databases without issue, so I'm puzzled why this particular database returns an error.

Thanks!

**Comment by nutterb** [comment]
I apologize that it's been so long for me to respond. I have seen some weird things happen with the metadata export, and this looks similar to those other problems.  My suspicion is that there are abnormal characters (such as bullet points imported from MS Word) that may be causing the meta data export to come back empty.

My best suggestion at the moment is to make a copy of your project, download the data dictionary, and run it through `cleanseMetaData`.  Then reload the cleansed meta data file into the copy of the project.

**Comment by baderstine** [comment]
I have the same error but for a different field.  

```
> df = exportRecords(rcon = rcon)
Error: $ operator is invalid for atomic vectors
> traceback()
4: unique(meta_data$form_name)
3: sprintf("%s_complete", unique(meta_data$form_name))
2: exportRecords.redcapApiConnection(rcon = rcon)
1: exportRecords(rcon = rcon)
```

**Comment by grauzerj** [comment]
Benjamin,
Thank you for your response.  As you mentioned, special characters appeared
to be the issue in one of my databases.  I narrowed down the fields and
found it to be a "copyright" symbol.  After removing that symbol, the
exportRecords function worked properly.

**Comment by nutterb** [comment]
@baderstine That isn't what I typically expect, but it may be the return of an error message.  Could you look share that data frame with me, if you can confirm that you have no protected information inside all that HTML?

**Comment by baderstine** [comment]
Ah, not your fault.  I went to the API Playground for our redcap instance and got similar errors running the example requests.  That seemed really odd, so I contacted our institutional Redcap IT folks and they forgot to tell me that the URL for API requests is different from the one listed in the API documentation (argh!).  With the correct URL, requests work as expected.
