### ISSUE TITLE
Import Files in Repeat Instance

### ISSUE THREAD

**Issue by MingBeres4d** [nutterb/redcapAPI#127]
Hello,

I want to import files into REDCap records with the package redcapAPI. But in my REDCap project, each record has several repeating instances, and I could only import file into the first instance. 
The most recent requirement for REDCap file import is: 
<img width="894" alt="screen shot 2019-01-30 at 4 46 32 pm" src="https://user-images.githubusercontent.com/41597747/52022676-d3554100-24ae-11e9-8fb5-f106232de9a5.png">
Is that possible for package redcapAPI also have the function to import files into different repeating instances? 

Thank you very much!

**Comment by nutterb** [comment]
The repeat_instance header wasn't  a feature when this was developed.  I have tried adding it to importFiles. If you wouldn't mind trying it out and verifying that it works as you expect, I'd appreciate that.

the development code can be loaded with 

`devtools::install_github("nutterb/redcapAPI", ref = "devel")`

**Comment by mattoslmp** [comment]
I try download devtools::install_github("nutterb/redcapAPI", ref = "devel") and I get following error:
Downloading GitHub repo nutterb/redcapAPI@devel
Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/nutterb/redcapAPI/tarball/devel'
