### ISSUE TITLE
Export_records hash identifiers and date shift options

### ISSUE THREAD

**Issue by Mkang1204** [nutterb/redcapAPI#128]
Dear all,

I was trying to export the records with hashed id and date shift using the redcapAPI package, but I didn't find the right function to implement that as what I find in the REDCap use interface. may I know whether it is feasible through the package functions? Thank you!

![image](https://user-images.githubusercontent.com/28990623/53111080-0a44d280-3502-11e9-8e97-48472aa66bb9.png)

**Comment by nutterb** [comment]
This is not something that can be accomplished through the API at this time. I am limited with what I can do in this regard, as the options to hash and date shift are not available through the API parameters.

However, the API does honor the settings for the user. So if you temporarily (or permanently) change your user settings to get deidentified data with both hashed user names and shifted dates, the API calls will give you the appropriate data.
