### ISSUE TITLE
Empty set error for "random" when using the allocationTable function

### ISSUE THREAD

**Issue by orangepeel97** [nutterb/redcapAPI#13]
Hi! I'm trying to create an allocation table with the following code, taken from this [Wiki page](https://github.com/nutterb/redcapAPI/wiki/Randomization-Module):

Randomize <- allocationTable(rcon, random="Randomization", 
                             strata=NULL, 
                             dag.id=c("[X]", "[Y]"), 
                             replicates=200, 
                             block.size=c(8, 4, 2), 
                             block.size.shift = c(0, .48, .9),
                             seed.dev=205, seed.prod=1510,  
                             bundle=proj)

No matter what I do with "random" (leave it blank, put random=NULL, or what I did above, which is to put the field name of the variable we want randomized), I get the following error:

Error in allocationTable(rcon, random = "Randomization", strata = NULL, dag.id = c("[X]",  : 
  1 assertions failed:
 * Variable 'random': Must be a subset of the empty set, i.e. also empty.

Could someone explain to me (in simple terms, please, I'm not a mathematician or coder) what this means and how to fix it? Thanks!

**Comment by nutterb** [comment]
The error message would have been thrown here: https://github.com/vubiostat/redcapAPI/blob/main/R/allocationTable.R#L173

It looks like it was finding no field names in the data dictionary. Which is weird.  I'm not sure what to think of that.

**Comment by spgarbet** [comment]
@orangepeel97 Is this still an issue? Did you figure out a resolution?

**Comment by nutterb** [comment]
Our current tests are passing, and I haven't been able to replicate the problem.
