### ISSUE TITLE
FUN(left) : invalid argument to unary operator

### ISSUE THREAD

**Issue by peterolejua** [nutterb/redcapAPI#134]
Hello,

I'm doing

```{r}
rcon <- redcapConnection(
  token = "***"
  )

raw_data <-- exportRecords(rcon)
```
And I get this traceback

Error in FUN(left) : invalid argument to unary operator
3. eval(f)
2. eval(f)
1. Ops.data.frame(exportRecords(rcon))

**Comment by wibeasley** [comment]
Hi @peterolejua, to help @nutterb, could you walk through the [troubleshooting steps](https://ouhscbbmc.github.io/REDCapR/articles/TroubleshootingApiCalls.html#exporting-from-redcap-to-r-using-redcapapi) from the beginning through the end of the 'redcapAPI' section.  If that doesn't clear up the problem, tell him your version of REDCap and redcapAPI.

**Comment by nutterb** [comment]
Do you have a url in your call to `redcapConnection`?

**Comment by nutterb** [comment]
I'm closing this for now.  Please let me know if the problem persists after adding your site URL.
