### ISSUE TITLE
exportRecords_offline() error

### ISSUE THREAD

**Issue by chillywings** [nutterb/redcapAPI#135]
Hi, 
So I'm trying to use the offline version of exportRecords. I've set the working directory to my file location, created objects containing character strings with the names of the data and meta data csv files. When I run exportRecords_offline, it returns the following error:
    `Error in `[.data.frame`(utils::read.csv(datafile, stringsAsFactors = FALSE,  : 
      undefined columns selected`

The data was downloaded from a Redcap report and the dictionary was downloaded from the Data Dictionary tab. Are these not appropriate data sources? I was using filters in the Redcap report and I tried exporting the complete data set, but that returned the same error.
Thanks!

**Comment by nutterb** [comment]
Thanks for the merge requests.  These are incorporated into master.
