### ISSUE TITLE
Labels with html tags

### ISSUE THREAD

**Issue by RaymondBalise** [nutterb/redcapAPI#137]
I am trying to import data that has html tags in the label.  For example: 

`<p style="margin-left: 40px">Please specify the other FDA-approved medications for opioid use disorder this facility/asset prescribes`

Yes it is malformed and missing the closing tag and I can't fix it... 

The label attribute on the variable in R looks like this:
`[1] "<p style=\"margin-left: 40px\">Please specify the other FDA-approved medications for opioid use disorder this facility/asset prescribes"`

Is it possible to have the api drop html tags from the labels?  The manual export removes them  automatically.

**Comment by wibeasley** [comment]
>Is it possible to have the api drop html tags from the labels? 

@RaymondBalise, what happens when you pass `labels = FALSE` to [`exportRecords()`](https://cran.r-project.org/web/packages/redcapAPI/redcapAPI.pdf)?

**Comment by nutterb** [comment]
I don't have anything that attempts to remove HTML from the label during the export, and I would be hesitant to implement something along those lines.  It's hard to know when that is prudent in the general case.  I'd suggest this is something better handled in post-processing.  The following loop does a pretty good job of stripping HTML tags.

```
# DF is your data frame
# Code adapted from https://stackoverflow.com/questions/17227294/removing-html-tags-from-a-string-in-r

for (i in seq_along(DF)){
  attr(DF[[i]], "label") <- 
    gsub("<.*?>", "", get_label(DF[[i]]))
}
```

**Comment by RaymondBalise** [comment]
I agree that it would be dangerous to do it by default but as it stands the output coming from the manual export is inconsistent with the API.  If you can see the code that feeds the manual export, adding the same functionality, as an option for the API call, would be good.  If you don't want to go that route, consider adding that nice little helper function into the `labelVector` package.

**Comment by nutterb** [comment]
Unfortunately, the intent for `redcapAPI` was to primarily make simplified access to the API calls. Mirroring what is available in the manual exports is not something I'm prepared to tackle with the limited development time I have available to me. 

The primary features I hope to make available are those given in the API documentation at https://redcap.[your_institution]/api/help/?content=default. All of the other bells and whistles that are available came about when I was working at an institution that used REDCap and had more time that I could dedicate to development. 

I'm hoping that I'll be able to spend a 4-6 hours per month in the coming year getting caught up on development. I can't promise I'll be able to prioritize a solution to this particular issue.

**Comment by RaymondBalise** [comment]
Sounds good.  Thank you for your lovely work!
