### ISSUE TITLE
export Pdf massert error

### ISSUE THREAD

**Issue by jobrycki** [nutterb/redcapAPI#138]
Hello,

I am using the exportPdf command from redcapAPI (version 2.2). I would like to download a pdf of one data collection instrument for one study ID.

I receive this error:

Error in massert(~filename + record + events + instruments, fun = checkmate::assert_character,  : 
  Assertion on 'unfixed_name' failed: Must be a subset of {'filename','record','events','instruments'}, but is {'dir','filename'}.

I specified the rcon in a previous command, and all the other options I have listed in the exportPdf command using single quotes. Using generic labels, my command looks like:

exportPdf(rcon,'directory',filename='redcap_forms_download',record='recordID',events=NULL,instruments='instrument name',all_records=FALSE)

Any suggestions are greatly appreciated!

**Comment by nutterb** [comment]
It looks like I failed to include an argument in the assertion.  Please try running `devtools::install_github('nutterb/redcapAPI', ref = 'devel')` and try running your code again.

**Comment by jobrycki** [comment]
Thanks for the edit. Your new code for the function worked great.

A separate question that came to mind, and I can open this as a separate comment if that's better, is whether the returnFormat should be set to csv or json. I've seen both used which is why this issue came to mind. I tried both approaches in the exportPdf function and both successfully exported PDFs so there didn't seem to be any difference between the two in the function.

Thank you again for your help.

**Comment by nutterb** [comment]
redcapAPI only ever uses 'csv'. If you specify `returnFormat = 'json'` in the function call, it ignores it for use of 'csv' instead.  This is mostly convenient for me, as I only have to maintain one type of behavior.  I don't see a need to change it unless there is some compelling performance increase from using 'json'
