### ISSUE TITLE
deleteRecords function missing 

### ISSUE THREAD

**Issue by kdurst2013** [nutterb/redcapAPI#149]
Currently the deleteRecords is not showing up as a part of the package. Is anyone else having this issue?

**Comment by nirshl** [comment]
use redcapAPI:::deleteRecords.redcapApiConnection()

**Comment by nutterb** [comment]
Thanks, I had forgotten to export the functions.  This is available now by installing `devtools::install_github("nutterb/redcapAPI", ref = "devel")`.  I'll have it in the main branch by the end of the day.
