### ISSUE TITLE
exportRecords returns incorrect field type

### ISSUE THREAD

**Issue by SimpleAddress4390** [nutterb/redcapAPI#15]
We are finding that text field where no data has been entered in a form for that field, are returned as logical instead of the correct field type from the metadata.

Once data are entered in the field on any record, the export correctly returns the field as chr.

Factor fields, even when blank on the entire form, are returned correctly, as are date fields.

Attached are screenshots for redcapR and REDCapAPI.  Help!!
[scrREDCapExtractions-20220718.pdf](https://github.com/nutterb/redcapAPI/files/9306939/scrREDCapExtractions-20220718.pdf)

**Comment by spgarbet** [comment]
https://github.com/vubiostat/redcapAPI/issues/10

https://github.com/vubiostat/redcapAPI/issues/25

**Comment by nutterb** [comment]
redcap 2.7.0 (https://github.com/vubiostat/redcapAPI/pull/70) add exportRecordsTyped, which is what is being recommended over exportRecords. 

Please see https://github.com/vubiostat/redcapAPI
