### ISSUE TITLE
importRecords() throws an error for Checkbox fields

### ISSUE THREAD

**Issue by vildead** [nutterb/redcapAPI#151]
Related to #110 

REDCap version 9.5.23
redcapAPI version 2.3
R version 3.6

I have checkbox field named **abc** with codes checkboxes 1, 2, 3, 4. My columns are thus named **abc___1**, **abc___2**, etc...

While importing, I get an error 
```
The variables abc___1, abc___2, ... do not exist in the REDCap Data Dictionary
```

I have tested the manual import - it works as expected.

**Comment by nutterb** [comment]
Presumably fixed with #156.  Please respond if that is incorrect.
