### ISSUE TITLE
process new data if REDCap API response is modified

### ISSUE THREAD

**Issue by gadepallivs** [nutterb/redcapAPI#155]
Is there a way to process new data instead of reading the entire data from REDcap API ? Learnt that some header information such as Etag, if-modified would help executing data processing steps instead of running repeated . 
is there any similar header information we pass to redcap ?

**Comment by nutterb** [comment]
Not that I am aware of. If it is possible, I would suspect it would have to be done through the data base, and `redcapAPI` doesn't support calls through the database.  If it were done through the API, I would think it would require multiple API calls, which might negate the advantages of only downloading the new subset. 

But even if it were possible, it would be a fairly new feature to REDCap, and I wouldn't have had time to implement its use.
