### ISSUE TITLE
Problem with checkboxes with values that contain upper case letters

### ISSUE THREAD

**Issue by NikNakk** [nutterb/redcapAPI#156]
REDCap converts uppercase checkbox values to lower case, but this isn't reflected by the code in this package. This causes problems with both `importRecords` and `exportRecords`.

Possibly related to #151, though that issue mentions numeric values.

**Comment by nutterb** [comment]
Thank you for identifying and fixing this.  It may be a while before I get this to CRAN, as I have limited development time and I should work on some other fixes before I put a CRAN release out.  I'm always looking for good collaborators that may be interested in tackling some of the issues. If you're willing, I'm more than happy to add contributors in the DESCRIPTION file.
