### ISSUE TITLE
importRecords fails when there are columns with numeric or integer constraints and missing values

### ISSUE THREAD

**Issue by NikNakk** [nutterb/redcapAPI#167]
The existing code breaks when importing records that include numeric or integer columns that contain NAs.

**Comment by baderstine** [comment]
Yep.  Try to run `importRecords()` with a redcap field that is defined as Text Box and Validation set to "Number".  If your input dataset has missing data, I get the following error:
```
Error: Assigned data `""` must be compatible with existing data.
ℹ Error occurred for column `<name>`.
x Can't convert <character> to <double>.
```

**Comment by MBeresf4d** [comment]
Hi @baderstine,  I got the same error before. 
I was using a list of record id from a xlsx file to export data from redcap, attach new record id from the same excel file, and then import into another redcap project. When importing records, I got the same error massage. 
I changed xlsx file to a csv file, and then was able to import records successfully.
