### ISSUE TITLE
504 Gateway Time-Out When Using importRecords()

### ISSUE THREAD

**Issue by cymonegates** [nutterb/redcapAPI#18]
Hello,

I keep getting the error message below when using importRecords(). The data get successfully imported into R but the error persists. This only occurs when importing a larger # of records (~5,000). Is there a maximum number of records the action can handle?

**Code used**
```
importRecords(rcon_tests,data=updateFac,overwriteBehavior = c("normal"),
              returnContent = c("count"), returnData = FALSE,
              logfile = "")
```

**Error**
```
Error in redcap_error(x, error_handling = "error") : 504: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>
```

**Comment by nutterb** [comment]
Good grief. It took me way too long to notice this. Up until https://github.com/vubiostat/redcapAPI/pull/67, batched import has always been broken. It looks like it would actually do the import, but wasn't saving the response from the server and throwing the error. 

https://github.com/nutterb/redcapAPI/commit/b04b6531587eb7ffd3eb3af71aa4c01ed444a22d#diff-f18d9fc3a7bbea0bad16fb4f9825490671ff4ec5868ce6544a71fc71c8975e26L315-L319
