### ISSUE TITLE
importRecords not assigning DAGs

### ISSUE THREAD

**Issue by saraputnam** [nutterb/redcapAPI#19]
I am exporting a report (using exportReports) with dag = TRUE.  The redcap_data_access_group variable appears in the dataframe, but when I use importRecords to import the dataframe into another REDCap project (with the same DAGs), none of the records are being assigned a DAG.  When I export the dataframe as a .csv and import it manually, the DAG is assigned.  

Is there a parameter I need to add to importRecords to get the DAGs to assign correctly?  Has anyone else had this issue?

Thanks!

**Comment by nutterb** [comment]
@spgarbet I believe this is resolved now, but we wouldn't have written any tests for it. Is setting up DAGs within a single institution a thing?

**Comment by spgarbet** [comment]
I asked a project manager and they said this is done frequently.

**Comment by nutterb** [comment]
Resolved via https://github.com/vubiostat/redcapAPI/commit/4f394f6024cd78687c9a7a0a79c0dc76de84fac6
