### ISSUE TITLE
exportRecords no longer working

### ISSUE THREAD

**Issue by Wunsei** [nutterb/redcapAPI#21]
A week ago, my code (which had been working perfectly) stopped working. When I run the `exportRecords` function, I get the error

```
Error in redcap_error(x, error_handling = error_handling) : 
  400: ERROR: An unknown error occurred. Please check your API parameters.
```
I suspect a RedCap update caused this, but I'm not sure. What's going wrong here?

**Comment by nutterb** [comment]
redcap 2.7.0 (https://github.com/vubiostat/redcapAPI/pull/70) add exportRecordsTyped, which is what is being recommended over exportRecords.

Please see https://github.com/vubiostat/redcapAPI
