### ISSUE TITLE
Read/Write record lock status?

### ISSUE THREAD

**Issue by baderstine** [nutterb/redcapAPI#23]
I'm looking for a way to lock/unlock records in bulk using the API.  I found this similar project - https://github.com/lsgs/redcap-locking-api - but cannot find the functionality in the R API.  Has anyone explored this?

**Comment by nutterb** [comment]
@spgarbet , this looks like something that might be theoretically possible, but isn't actually supported by the REDCap API.  Are you interested in incorporating off-label uses into redcapAPI?

**Comment by spgarbet** [comment]
If the REDCap API interface supports it, then we should probably include it.

**Comment by nutterb** [comment]
My question was more directed toward the fact that this _isn't_ supported by the REDCap API interface. It looks like those who have managed to do it are mimicking the call that the UI uses to set the lock on a record. 

But the formally published API interface doesn't have a method for this.

**Comment by spgarbet** [comment]
Interesting. We could theoretically do the same for the `sql` handling as well. It's a risky road to start going outside the official API.

**Comment by nutterb** [comment]
After a discussion offline, we've determined pursuing this for locking records is not within our interests. If it becomes a part of the official API, we will incorporate it then.

**Comment by spgarbet** [comment]
There is still some benefit the library could provide. The makeApiCall could become exported and then the retry on a connection would included. The API_KEY and all would be managed consistently.

**Comment by nutterb** [comment]
As it turns out, we're already exporting makeApiCall to the user. 

https://github.com/vubiostat/redcapAPI/blob/main/NAMESPACE#L97
