### ISSUE TITLE
Problem with exportSurveyParticipants

### ISSUE THREAD

**Issue by esantucci** [nutterb/redcapAPI#24]
Please, 
Can someone help me? I'm trying to export the Survey Participants Lists with the survey link but this error appears: 
Error in checkmate::assert_data_frame(x = arms_data, ncols = 2, add = coll) : 
  argument "arms_data" is missing, with no default

Thanks

**Comment by nutterb** [comment]
It appears this was corrected before transferring ownership to https://github.com/vubiostat/redcapAPI
