### ISSUE TITLE
exportRecords() not exporting all data

### ISSUE THREAD

**Issue by slb2240** [nutterb/redcapAPI#26]
Hi, I am trying to export data from REDCap to R using the exportRecords() function. While most of the data are fully exported, two variables appear to be only partially exported, as in the data populated for these variables is incomplete. Specifically, these variables are populated for nearly all patients in REDcap, but missing for most (but not all) patients in the exported data. Have you ever seen this before? Or do you have any suggestions on how to approach this? Thank you!

**Comment by nutterb** [comment]
Possibly related: https://github.com/vubiostat/redcapAPI/issues/24

**Comment by nutterb** [comment]
redcap 2.7.0 (https://github.com/vubiostat/redcapAPI/pull/70) add exportRecordsTyped, which is what is being recommended over exportRecords.

Please see https://github.com/vubiostat/redcapAPI
