### ISSUE TITLE
Importing with autonumbering

### ISSUE THREAD

**Issue by jthomas08** [nutterb/redcapAPI#29]
How do we use the importRecords  so that we can have REDCap import the record id's with what's available? Basically I need to use the forceAutoNumber parameter of the REDCAP API.

**Comment by nutterb** [comment]
This has not been resolved. redcapAPI is not providing an interface to the following API parameters 

* forceAutoNumber
* dateFormat
* csvDelimeter (I'm not sure we need to, since we are controlling the conversion of the data frame to CSV)

**Comment by nutterb** [comment]
Corrected via https://github.com/vubiostat/redcapAPI/pull/77
