### ISSUE TITLE
curly quotes and other miscreant characters

### ISSUE THREAD

**Issue by wibeasley** [nutterb/redcapAPI#32]
@nutterb, just a heads up.  I've had two recent issues created that ended up being caused by curly quotes in the data dictionary.  The [solution](https://github.com/OuhscBbmc/REDCapR/commit/7367180641158d6ef6cae39ac4886efb43248e36) involved being more explicit with the text & encoding passed to `httr::content()`.  

I know you use `httr::POST()` instead (and I like that there are two approaches available to the public) and I don't know if there's an analog for your approach.  Maybe `httr::POST()` avoids it entirely. 

If you start seeing things like these two REDCapR issues, it may be worth investigating.  It may address redcapAPI's nutterb/redcapAPI#126 & nutterb/redcapAPI#129?

* https://github.com/OuhscBbmc/REDCapR/issues/269
* https://github.com/OuhscBbmc/REDCapR/issues/272

**Comment by nutterb** [comment]
Kind of similar to https://github.com/vubiostat/redcapAPI/issues/24, but not HTML

**Comment by nutterb** [comment]
redcap 2.7.0 (https://github.com/vubiostat/redcapAPI/pull/70) add exportRecordsTyped, which is what is being recommended over exportRecords.

Please see https://github.com/vubiostat/redcapAPI

We expect this to have better handling for UNICODE.
