### ISSUE TITLE
exportFiles has trouble finding the record ID

### ISSUE THREAD

**Issue by nutterb** [nutterb/redcapAPI#34]
I keep getting errors that there is no file for the record when I know there is one.

**Comment by spgarbet** [comment]
This may be related to the gist I sent you. https://gist.github.com/couthcommander/e379c7c2c91a40e529052574dd12475c

**Comment by nutterb** [comment]
I have low confidence these are related. I've never worked with a file repository before. 

In a separate e-mail, I stated

> I'm ashamed to have submitted this issue with no details on how to reproduce it. You should probably cancel it and flog me with its dead carcass.

That's still my recommendation.

**Comment by spgarbet** [comment]
Let's just close this one.
