### ISSUE TITLE
New API methods for 7.4.14 (at least that's when I see it)

### ISSUE THREAD

**Issue by nutterb** [nutterb/redcapAPI#35]
- [x] `importArms`
- [x] `deleteArms`
- [ ] `importEvents`
- [ ] `deleteEvents`
- [ ] `importMetaData`
- [ ] `createProject`
- [ ] `importProjectInfo`
- [x] `generateNextRecordName`
- [x] `deleteRecords`
- [x] `exportSurveyParticipants`
- [ ] `importUsers`

**Comment by nutterb** [comment]
@spgarbet If any of the remaining methods are desired, perhaps each one could have a separate issue submitted on your repo.

**Comment by spgarbet** [comment]
I shared a tar ball of code for "createProject" with you from a specification.

**Comment by spgarbet** [comment]
Oh, we have another project that is doing the importUsers.

**Comment by nutterb** [comment]
Any additional methods will be handled in separate issues in the vubiostat repository.
