### ISSUE TITLE
REDCap API doesn't return duplicate ID error in some versions

### ISSUE THREAD

**Issue by nutterb** [nutterb/redcapAPI#36]
We can alleviate this by building in a check for duplicate identifiers and casting an error when it occurs.  "Duplicate identifiers" will need to account for `record_id` and `redcap_event_name`.  Are there other identifiers (that will appear conditionally) that we need to account for?

Nothing comes to mind, but I don't want to code something that can't account for additional identifiers.

**Comment by spgarbet** [comment]
I've seen duplicate ids playing around in our sandbox test REDCap project. It wasn't a problem for me. Is there a reproducible example of this?

**Comment by nutterb** [comment]
Doubtful. I'd have to look at REDCap change logs, but I'm guessing this has probably been fixed several versions ago.

**Comment by spgarbet** [comment]
I think this isn't an issue anymore either.

**Comment by nutterb** [comment]
I'm inclined to agree. I seem to have lost my access to the REDCap Community, so I can't see all the release notes.
