### ISSUE TITLE
Potential bugs in REDCap

### ISSUE THREAD

**Issue by nutterb** [nutterb/redcapAPI#37]
I'm compiling notes here because I have no better place to do it where I can keep track of it.  It wouldn't hurt to have someone confirm the behavior.  However we decide to handle these issues needs to be documented as well.
- In `exportFieldNames`, if you give a vector of field names, it returns "ERROR: Invalid field."  But the REDCap documentation states that it will accept multiple fields.  Until this gets fixed, I suspect the appropriate behavior would be to honor the `fields` argument only when it has length 1, and print a message that the entire field list is being returned until the REDCap API is corrected.
- `exportFieldNames` also doesn't return field names for calculated values, sliders, or signature draws.  I think it probably should--note that REDCap disagrees.  They document that the calculated fields, signatures, files, and descriptive fields are not included because they cannot be used in data imports.  It would be nice to have an option to get these anyway, as it could help streamline the process of formatting variable names upon export.  Then again, the time spent sending the request to the API is probably longer than the time spent parsing things through regex, so I probably won't ask them to change this.
- In `exportArms`, if you use the `arms` argument, the API returns an empty data frame
- In `exportEvents`, if you use the `arms` argument, the API returns an empty data frame

**Comment by spgarbet** [comment]
My experience is the `arms` argument does not work. `arm` is the only thing supported. I.e., one can only specify a single arm.

**Comment by nutterb** [comment]
I don't believe that to be true anymore. That should have been fixed in https://github.com/vubiostat/redcapAPI/pull/38

I get the proper response from exportArms(rcon, arms = c("1", "2"))

**Comment by spgarbet** [comment]
Interesting.

**Comment by nutterb** [comment]
We've fundamentally changed how we parse vectors to arrays for the API. That seems to be the foundation of the reported issues.
