### ISSUE TITLE
exportUsers() doesn't always apply permissions formats correctly

### ISSUE THREAD

**Issue by nutterb** [nutterb/redcapAPI#4]
In some databases, I'm seeing the user name applied as a row name and the variables are shifted to the left one column.  The user permissions for each form don't get properly labelled.  I wonder if this might be related to the version in which the database was built (but it shouldn't)

**Comment by SteveLane** [comment]
Aware this is an old issue, but I'm just starting to go through some of these (very slowly...)
Is it still an issue for you? I've just tested on a development project and could not replicate. I added new users, then tested the export after some had accessed the project and some hadn't. Still had an appropriate return via exportUsers()

**Comment by nutterb** [comment]
It's only ever been an issue in one database, and it was a pretty old database that got carried over a couple of versions of REDCap.  I've never been able to duplicate it.  I'm happy to close this unless it comes up as a problem again.

**Comment by SteveLane** [comment]
Worth closing then:)
