### ISSUE TITLE
Batched calls by users with limited access

### ISSUE THREAD

**Issue by nutterb** [nutterb/redcapAPI#49]
I noticed this in reading some of @OuhscBbmc 's issues on REDCapR.  Currently, `redcapAPI` will, I think, happily try to batch together all of the pulls for a user with limited data access.  But the hashed ID's aren't likely going to make any sense.  We might want to work on that.

By the way, I just got access to Vanderbilt's plugins REDCap.  So I can do some development again.  Yay!

I'm going to file a few issues to note the API methods that don't currently have R methods.  I might try to pick some of those off.  I may be asking for help to elaborate on when these functionalities became available so that we can cut off attempts to access them before they go to the API.

**Comment by SteveLane** [comment]
Sure - I have to confess that I haven't yet been able to chuck time into development yet, but hopefully will be able to over the next couple of months.

**Comment by nutterb** [comment]
@SteveLane are you able to pull data through your API.  I keep getting an error that says `error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure`.  I suspect it's a local configuration issue because I can get data through the POSTMAN app, but I can't connect on my computer.

**Comment by SteveLane** [comment]
@nutterb Yes I can, at least internally whilst behind my orgs firewall (with ssl.verifypeer = 0).

**Comment by nutterb** [comment]
I've incorporated this into version 2.0.0
