### ISSUE TITLE
Export List of Export Field Names

### ISSUE THREAD

**Issue by nutterb** [nutterb/redcapAPI#50]
Need a method for this functionality.

At version of REDCap was this introduced?

**Comment by SteveLane** [comment]
Hey @nutterb - can you send me an email from your new address please?

**Comment by SteveLane** [comment]
Functionality addressed by https://github.com/nutterb/redcapAPI/commit/2b2363f954a00f3af56a1765a975441c1412852f

**Comment by nutterb** [comment]
Consolidated into Issue #65.

I kept your source code in what I have done.  It's still local on my machine though.  I'll probably push it up to the repo later tonight.
