### ISSUE TITLE
Adding an argument to `allocationTable`

### ISSUE THREAD

**Issue by nutterb** [nutterb/redcapAPI#59]
I just got asked to do a randomization in REDCap that is using a 3:1 matching ratio.  I was all excited to fire it up with `allocationTable` but then realized that `allocationTable` assumes a 1:1 matching ratio.  Are there any objections to me adding an argument `weights` to the function that allows you to set the ratio?

It would work like this: if the two groups are `Control` and `Treatment`, and we wanted 3 controls for every treatment, we would pass `weights = c(3, 1)`.  Then when we generate the sample, we translate that to `sample(c('Control', 'Treatment'), n, probs = c(.75, .25))` 

I guess for backward compatibility, I need to add the `weights` argument after the `proj` argument.  unless that's really too awkward.

What say ye?

**Comment by wibeasley** [comment]
For the function signature, think about accepting a *named* vector, where a names is the condition associated with each probability.
```r
bla bla, weights=c("Control"=3, "TreatmentA"=1, "TreatmentB"=1), bla bla
```

That way, it would generalize well beyond two groups, and it would be really hard for the caller to pass names that don't match with their weights.

FWIW, I don't think the probability weights have to sum to one, but you may want to force it to be that way
```r
> table(sample(11:13, size=100, prob=c(10, 1, 1), replace=T))

11 12 13 
78  9 13 
```

**Comment by nutterb** [comment]
That's an excellent idea.  I'm not sure I like forcing named vectors, but as a compromise, I can add to the output what the weight scheme was, that way it can be reviewed.  So if I passed `weights=c(1, 3, 1)` at least the output would tell me that the weights were

```r
   Control TreatmentA TreatmentB 
         1          3          1 
```
and I could decide if that's what I intended.  And of course _lots_ of documentation on that point.

Yay, more argument checks!  Perhaps this would be a good time to bring up `ArgumentCheck`?  (just kidding, I'm not sure `ArgumentCheck` is stable enough to put into anything yet).

**Comment by nutterb** [comment]
More feedback solicitations:

Would the following be enough in terms of error checks?  Am I missing anything in how people might use/abuse this?

```r
  #* 17. If 'weights' is not NULL, it is the same length as the number of levels in 'random'
  #* 18. If 'weights' has names, the names are identical to the levels of 'random'
  #* 19. if 'weights' doesn't have names, assume the weights were given in the order of levels(random)
```

**Comment by nutterb** [comment]
This works nicely in version2
