### ISSUE TITLE
Exporting form locking status

### ISSUE THREAD

**Issue by aghaynes** [nutterb/redcapAPI#60]
Hi,

Do you know whether its possible to export the form locking status either along side or separate from the data? This might be more of a REDCap question than a redcapAPI point...

Thanks

Alan

**Comment by nutterb** [comment]
@SteveLane, are you on the REDCap Google Group?  I don't recall the locking status being a retrievable field on the REDCap API, but that might have changed since April.

**Comment by SteveLane** [comment]
Hi @aghaynes (cc @nutterb), sorry for the late reply - been on leave without access to github.
Form locking status is not retrievable by any API methods as far as I can tell.
@aghaynes do you have access to the REDCap group or wiki? If not, I can add it as a request, but I'm sure the developers would want a few before adding it...

**Comment by aghaynes** [comment]
Hi, Sorry for the delay, I was away briefly. Yes, I have access to the REDCap group and wiki. I'll make a request.
Thanks, 
Alan

**Comment by wibeasley** [comment]
For the sake of continuity, @aghaynes's thread in the forums is https://groups.google.com/forum/#!topic/project-redcap/Q5OzxcygNYw.  (No responses yet.)
