### ISSUE TITLE
Update CRAN due to change of email address

### ISSUE THREAD

**Issue by SteveLane** [nutterb/redcapAPI#63]
@nutterb I've changed positions, so have updated email address on DESCRIPTION (which updated other documentation due to updates in roxygen2) (8c55d6c)

I don't see this change as posing any issues with package maintenance, as I should be able to get access to another REDCap server (but still have access to my previous one for the moment).

**Comment by nutterb** [comment]
Congratulations on the new position!

We'll just need to remember to notify CRAN of your change in e-mail prior to submitting to CRAN again (whenever that is).  They won't accept a submission with a different maintainer's e-mail address without being notified first.

**Comment by nutterb** [comment]
@SteveLane could you send an e-mail to CRAN letting them know that you will not be continuing as the Maintainer?  They will need that notification before I can update the package. (see https://github.com/nutterb/redcapAPI/issues/70)

Thanks.

**Comment by SteveLane** [comment]
Done - sorry it's taken a few days, been on leave.
