### ISSUE TITLE
fields and forms arguments to exportMetaData

### ISSUE THREAD

**Issue by nutterb** [nutterb/redcapAPI#64]
Is it just me, or does the `fields` and `forms` arguments to the API for exporting meta data not do anything?  Even when I use them in POSTMAN I get the full data dictionary.

@SteveLane @wibeasley

**Comment by wibeasley** [comment]
You're right.  At least for a few attempts on my 6.9.7 server.  Do you have access to the forums?  If not, I'll post whatever you send me on your behalf.

You petitioned for access to Vandy's test server, but not the forums?  If you want, I'll try to talk to someone to get you access to that.  With as much time you dedicate to the community with redcapAPI, it's certainly in everyone's interest that you aren't working with one hand tied behind your back.  It won't radically change any thing for you, but it would help at least a little.

**Comment by nutterb** [comment]
You know what, if I could remember my password, I'm sure I could.  My Cleveland Clinic email is still active. But that will only last for a few months, and I seem to have locked myself out of that account.

But I do still have access the the source code for now.  I don't know if that will go away at all.  But that will let me file the bug report.  I just wanted to make sure I wasn't the only one.
