### ISSUE TITLE
Remove redcapDbConnection methods

### ISSUE THREAD

**Issue by nutterb** [nutterb/redcapAPI#66]
How do you feel about scrapping the `redcapDbConnection` methods?  I'm pretty sure no one uses them.  If someone tried, I'm pretty sure they would have failed after all the changes I made to `fieldToVar`.  It seems we would have heard by now if anyone was trying to use it.

I know it isn't really good to sabotage backward compatibility like this, but I honestly don't think they would work as they are given, and I have no way of actually developing them.

**Comment by wibeasley** [comment]
I think it's a good idea for several reasons.  I'm guessing that Jeff wrote that before the API was even available.  It's certainly not what the REDCap development team promotes now.  In fact, they kinda groan at a conference when someone suggests a solution that involves talking directly to MySQL.

@aarenson, you have a better pulse on what REDCap administrators do.  Is there any reason for @nutterb and @SteveLane to support this?

Occasionally I'll write something that hits MySQL, but those are the types of things that you'd never want to support.  

If you do shut it down, consider writing a deprecating warning, and some short instructions how the could use `devtools` to get the last version of redcapAPI that supported that.

**Comment by SteveLane** [comment]
I think it makes sense to deprecate it. I too am of the opinion that interfacing directly with the database is dangerous.
I would think that most administrators would only allow a local connection to the DB anyway, which would restrict most users (thinking of my situation anyway).

**Comment by aarenson** [comment]
I'm not sure I have any insight about what the consortium does as a whole that y'all don't have, but for what it's worth, I wholeheartedly agree that it's a bad idea to support direct access to the database.

**Comment by nutterb** [comment]
Honestly, given the choice, I'd prefer to connect to the database directly, and suspect it would be a bit faster. But I've been persuaded in the past few months to make use of stored procedures over SQL injection, and there's no good way to implement that approach in an R package. 

I've removed the remaining Db methods from the version 2 branch.
