### ISSUE TITLE
Deprecating `redcapProjectInfo`

### ISSUE THREAD

**Issue by nutterb** [nutterb/redcapAPI#68]
Newer versions of REDCap have an export method `exportProjectInformation`, which is useful and for which I've coded a method.  But I can only imagine the confusion I'm going to create for myself if I have `exportProjectInformation`, which hits the API and `redcapProjectInfo`, which is a wrapper function for executing multiple API calls (such as getting the meta data, events, and arms).

I want to deprecate `redcapProjectInfo`, but I'm having a serious lack of creativity.  What do I call it's replacement.  The best thing I can come up with is `multiExport`, which is kind of dull.  Any thoughts on a better name?

**Comment by SteveLane** [comment]
`metaExport`?

**Comment by nutterb** [comment]
I like `metaExport` better than my idea. My only hesitation is the fact that we already have an export with a "meta". How do you feel about `exportBundle`?

**Comment by SteveLane** [comment]
Yes, I thought that too, but then considered it was at the end of the name rather than the start.
`exportBundle` is good.
