### ISSUE TITLE
We need a 1.4.0

### ISSUE THREAD

**Issue by nutterb** [nutterb/redcapAPI#70]
R Version 3.3.0 is due out in April, and I'm not going to have `redcapAPI` 2.0 ready in time for that release.  However, we need to make some changes in the existing codebase before R 3.3.0.  The big two issues are
1. Steve's e-mail address
2. Using the `::` notation for functions from `utils`.  

Those two should be simple enough.  I'll also try to code in a check to prevent a quirk in the API import that was reported yesterday.  I'll note that in a separate issue.

**Comment by nutterb** [comment]
Except for @SteveLane 's e-mail address, these are addressed in the Version2 branch.

**Comment by SteveLane** [comment]
Hi @nutterb - given my lack of involvement in this of late, I suggest that my name/email get taken off the maintainer list.
