### ISSUE TITLE
REDCAP API Usage

### ISSUE THREAD

**Issue by sunandxkannappan** [nutterb/redcapAPI#72]
Dear nutterb,

My name is Sunand Kannappan, a student at the Faculty of Medicine in the University of Calgary, Canada. I'm working on a patient database on REDCAP, and would like to export records through the REDCAP API. 

I have decided to use the REDCAP API with R-markdown/Knitr Packages, to create a properly formatted report (mandatory structure) for use after every patient visit so that I may file the report for mandated hard-copy repository. I have 3 different data collection instrument types - i) Patient ID, ii) Visit Form (there are several of these, about 15) and iii) Death.

I require to create a formatted word document report with fields from Patient ID, ONLY the latest Visit Form and potentially Death, each time I see a patient. There are few different formats of the report (all mandated to be of a specific structure).

I was wondering if you might be able to provide me with some direction on how I should move forward. If I should be using a different platform, please let me know. 

If you would be alright with having a short call to set me in the right direction, please let me know.

Thanks,
Sunand Kannappan

Cumming School of Medicine
Tom Baker Cancer Centre
Southern Alberta Cancer Research Institute
Phone: 403-473-8985

**Comment by nutterb** [comment]
It looks like you have already laid out a pretty good vision of where to take this.  I have implemented such work paths in the past and REDCap can be quite friendly with making such reports.

I don't mind giving some pointers on how to go about this.  I think it would be best if you contacted me by e-mail at benjamin.nutter@gmail.com to set up further discussions.
