### ISSUE TITLE
Import Data with Object-C

### ISSUE THREAD

**Issue by magicalccong** [nutterb/redcapAPI#75]
i can't find any document about Object-C...
Who can tell me how to work it out ? thanks

**Comment by nutterb** [comment]
This is the closest thing I found on a Google search. I am not familiar with Object-C, so I'm afraid I can't help with specifics. 

https://www.google.com/url?sa=t&source=web&rct=j&url=http://www.drmetts.com/resources/SCOR_abstract_final.pdf&ved=0ahUKEwj9_6XzoIzQAhUBeSYKHcIABrUQFggfMAI&usg=AFQjCNFOfkd5OEMLlYxxX9sG7sa0mpIpGA&sig2=iZOokwGBYNKV-rg5FfGVAA

If you are willing to code it yourself, I would explore libraries that can use the POST methof on Web forms. This is the backbone of exporting data from REDCap.

**Comment by magicalccong** [comment]
thanks
