### ISSUE TITLE
importRecords fails in specific conditions when there are 'time' fields

### ISSUE THREAD

**Issue by tobadia** [nutterb/redcapAPI#79]
Hi,
After toying around with the API, I've come into a small bug that causes `importRecords()` to fail when calling `chron::times()` in case there are absolutely no missing values in the fields of interest.

I've forked and fixed the thing and opened a PR just minutes ago. It seems to me it's just a matter of `lapply()` followed by `sapply()` rather than the two previous `sapply()`s.

I'm attaching a reproducible unit test that highlights this as a separate R script.

Hope that helps,
Thomas
[redcapAPI_importRecords_bugfix_unit_test.txt](https://github.com/nutterb/redcapAPI/files/667773/redcapAPI_importRecords_bugfix_unit_test.txt)

**Comment by nutterb** [comment]
I will take a look at this in the next week. Could you let me know what version of REDCap you use? I will want to check this on a couple versions to make sure this isn't a version specific thing (from the look of it, it isnt, but I want to be sure )

**Comment by tobadia** [comment]
Yeah sure. The server version in my institution is 6.15.0. 

Another thing I noticed, totally unrelated, is that sometimes metadata get scrambled and changes the separator  `" [|] "` to `"[|]"`, which then causes `validateImports()` to fail when mapping values to codes. This however is totally server-side and not really API related, although it might warrant a mention in the package documentation (e.g. in case one were to see nearly all dropdown/radio/checkboxes fields to yield errors while importing data)

**Comment by tobadia** [comment]
Hi,

Just checking in on things here. I'm running a locally-compiled version implementing the PR I proposed because otherwise it's impossible to `validateImport()` properly.
Did you have time to look into the (very) small changes and how they affect the rest of your routines ?

Best,
Thomas

**Comment by nutterb** [comment]
Sorry.  That time I did get distracted.  Your pull request seems to be working on other versions of REDCap, so I've merged it in.  

I'm working on a patch for the `" | "` vs `"|"`.  I'm pretty sure it will work and be safer if we split on `"|"` and then trim the white space off of it.  Should be back up in the main branch shortly.
