### ISSUE TITLE
exportRecords Error

### ISSUE THREAD

**Issue by bryceglarsen** [nutterb/redcapAPI#84]
Hello! Thank you for all the hard work. I'm working to combine various projects and had no issues with the first two. However, for the last two, I continue to encounter this error:
```
Error in if (grepl("date_", m$text_validation_type_or_show_slider_number) &&  : 
  missing value where TRUE/FALSE needed
```

I saw a similar issue posted previously, but can't figure out how/where to fix. Any help is appreciated!

**Comment by bryceglarsen** [comment]
Attached Data Dictionary.
[Year9DataDictionary_2017-02-15.csv.zip](https://github.com/nutterb/redcapAPI/files/778966/Year9DataDictionary_2017-02-15.csv.zip)

**Comment by nutterb** [comment]
It seems that I never accounted for the possibility of negative numbers as the coding behind a checkbox variable.  The API was converting `survey13_med1now` to `survey13_med1now____1` while the `redcapAPI` was looking for `survey13_med1now___-1`.  I've corrected this in `redcapAPI`.  Please run

`devtools::install_github("nutterb/redcapAPI")`

and let me know if that resolves the issue for you.

**Comment by bryceglarsen** [comment]
Thanks! This seems to be working. However, it seems to be exporting with the labels rather than raw data only for the survey that encountered the issue. I can manage with it as such having noticed that, but unsure if something that can be set within the exportRecords call (I didn't see this as an option) or within the package itself.

**Comment by nutterb** [comment]
I'm not getting the same behavior.  When I use

`exportRecords(connection, factors = TRUE)` I get the labelled data.  When I use `exportRecords(connection, factors = FALSE)` I get the unlabelled data.  In both cases, I see what I expect.  

Is it possible you're thinking that `labels = FALSE` would return the raw data (it does something different)?

**Comment by bryceglarsen** [comment]
Ah, my apologies! I truly thought I tried this (and admittedly did try Labels as well). This works like a charm. I truly appreciate your timeliness! This proved a great help as other packages were not providing the data in as clean of a format.

**Comment by nutterb** [comment]
No apologies necessary.  If I had a dollar for every time I'd done something similar, I'd be retired.  Thanks for reporting the issue.
