### ISSUE TITLE
exportReports Error

### ISSUE THREAD

**Issue by tsondger** [nutterb/redcapAPI#85]
When I try to export a using exportReport I receive an error regarding 'field_labels.'

Using the default settings with exportReports(rcon, report_id = 4605) I receive the following error
![image](https://user-images.githubusercontent.com/29311432/26987926-115c3f28-4d13-11e7-8164-d7d0e24e3d10.png)

The only reference to field_lables in the help documentation is in the checkboxLabels information which defaults to TRUE. Just to see if I would get different results I set it to FALSE pilot_report <- exportReports(rcon, report_id = 4605, checkboxLabels = F) and received a similar error
![image](https://user-images.githubusercontent.com/29311432/26988012-4fde430e-4d13-11e7-96d5-5f1a390ab73a.png)

Any suggestions?

**Comment by nutterb** [comment]
It's possible that this is a patched bug that hasn't been send to CRAN yet.  Please run `packageVersion("redcapAPI")`.  If you get anything less than `1.3.7` in return, then run `devtools::install_github("nutterb/redcapAPI")` and try running `exportRecords` again. 

Let me know if the problem persists.

**Comment by nkarduri** [comment]
I still see the problem

**Comment by nkarduri** [comment]
> library(redcapAPI) #Load the package into the current R session.
> rcon <- redcapConnection(url="XXXXXXXXXX/", token="XXXXXXXXXXXXXXX")
> output <-  exportReports(rcon,report_id=3383)
Error in if (grepl("date_", m$text_validation_type_or_show_slider_number) &&  : 
  missing value where TRUE/FALSE needed

**Comment by nkarduri** [comment]
Im running packageVersion("redcapAPI")
[1] ‘1.3.7’

**Comment by tsondger** [comment]
It looks like I was running version 1.3. I updated from GitHub and now show
version 1.3.7. However, I'm now getting replacement has 0 rows, data has
1645 when I use exportRecords, and when I use exportReport R pulls in the
report as a data frame, but when I try to view or use any other functions
on the report data frame I receive Error: `x` and `labels` must be same
type.

Travis Sondgerath, MS, MPH
Epidemiologist 1
Viral Hepatitis Program
Tennessee Department of Health

**Comment by amysheep** [comment]
I have the same problem after I updated my R to the latest version.
It works fine using older R versions but not in the new version.

**Comment by nutterb** [comment]
@nkarduri @tsondger @amysheep it's been a long time since this was reported. I believe it is working in Version 2.  Are any of you still trying to use this functionality and be willing to test if the new codebase works for your projects?

**Comment by amysheep** [comment]
Sure. I can test it out next week.
