### ISSUE TITLE
redcapFactorFlip not working properly

### ISSUE THREAD

**Issue by afleishman** [nutterb/redcapAPI#88]
I'm using redcapAPI v.1.3 and I'm consistently getting an error saying "This does not appear to be a REDCap factor." When I remove the '!' from the first 'if' statement the function it works perfectly. 

**FROM:** 
if (!is.null(redcapLabels) | is.null(redcapLevels))
        stop("This does not appear to be a REDCap factor.")
**TO:**
if (is.null(redcapLabels) | is.null(redcapLevels))
        stop("This does not appear to be a REDCap factor.")

![image001](https://user-images.githubusercontent.com/6239089/31635965-b988458c-b296-11e7-8f51-507f50073d6e.png)

**Comment by nutterb** [comment]
I just made the recommended change.  Please use `devtools::install_github("nutterb/redcapAPI")` and try again.

**Comment by nutterb** [comment]
Released with version 2.0

**Comment by afleishman** [comment]
Looks like this is an issue again. It appears the label attribute was assigned to '$redcapLabels' in the past and now the label attribute is assigned to '$levels' 

Changing the first line as follows should fix it:
function (v) 
{
    **redcapLabels <- attributes(v)$levels**
    redcapLevels <- attributes(v)$redcapLevels
    if (is.null(redcapLabels) | is.null(redcapLevels)) 
        stop("This does not appear to be a REDCap factor.")
    if ("factor" %in% class(v)) {
        v <- factor(as.character(v), redcapLabels, redcapLevels)
        v <- as.character(v)
        if (is.numeric(redcapLevels)) 
            v <- as.numeric(v)
    }
    else {
        v <- factor(v, attributes(v)$redcapLevels, attributes(v)$redcapLabels)
    }
    attr(v, "redcapLabels") <- redcapLabels
    attr(v, "redcapLevels") <- redcapLevels
    return(v)
}

**Comment by nutterb** [comment]
Think we got this worked out. Sorry for the mixup in the update. Please try `devtools::install_github("nutterb/redcapAPI")`

**Comment by afleishman** [comment]
Unable to dl the dev version, but I see my issue with `redcapFactorFlip()` -- It doesn't seem to work for checkbox variables since there is nothing stored in `$redcapLabels`.
