### ISSUE TITLE
Allow exportRecords to pass a colClasses argument to read.csv calls

### ISSUE THREAD

**Issue by tobadia** [nutterb/redcapAPI#90]
Hi @nutterb,
Upon working on a database with numeric identifiers that are forced to be 4-digits by a regex, I realize they get recasted to `as.numeric()` due to the use of 
`x <- read.csv(textConnection(as.character(x)), stringsAsFactors = FALSE, na.strings = "")` 
in `exportRecords.redcapApiConnection()`.

A quick fix would be to allow for the use of the `colClasses` argument to be fed into `exportRecords()` (defautling to NULL) and then passing it to every `read.csv()` call you have.

In my case here, I'm running checks to see if IDs match the specific format (which they should but you're never too sure) and I had all values below 1000 (basically, 0001 to 0999) recasted to numeric, thus dropping leading zeros. By hacking a bit your function and adding a name colClasses argument that matches my variable name, problem solved.

If you feel it's better that way, I can prepare a quick fork and PR !

Best,
Thomas

**Comment by nutterb** [comment]
This seems like a completely reasonable feature.  I would very much appreciate a pull request.

**Comment by tobadia** [comment]
Great, thanks. I'll fork on my laptop, likely tomorrow.

**Comment by tobadia** [comment]
Hi @nutterb. I've fixed a small error in my PR with default colClasses that was improperly set to NULL instead of NA. I'm also opening a separate issue for something else I just patched.
