### ISSUE TITLE
install/load Error: object ‘[.labelled’ is not exported by 'namespace:Hmisc'

### ISSUE THREAD

**Issue by januz** [nutterb/redcapAPI#94]
after updating all R packages (including `Hmisc`), I got the following error, when trying to load `redcapAPI`:

```

Error : object ‘[.labelled’ is not exported by 'namespace:Hmisc'
ERROR: lazy loading failed for package ‘redcapAPI’
```
reinstalling `redcapAPI` (from CRAN or Github) doesn't work either, giving the same error message

**Comment by nutterb** [comment]
This is a side effect of the unfortunate-for-me decision for `Hmisc` to no longer export the label assignment and extraction functions.  I have most issues fixed already, but I have one more thing to do before I submit an update tomorrow.

If you need to use `redcapAPI` in the meantime, you will need to install `Hmisc` 4.0-2. (https://cran.r-project.org/src/contrib/Archive/Hmisc/)

**Comment by januz** [comment]
Thanks for the info!
