### ISSUE TITLE
package or namespace load failed for ‘redcapAPI’

### ISSUE THREAD

**Issue by clelandcm** [nutterb/redcapAPI#95]
I have used redcapAPI several times a week for months (thank you for your work), and I am encountering a problem loading the package.

> library(redcapAPI)
Error: package or namespace load failed for ‘redcapAPI’:
 object ‘[.labelled’ is not exported by 'namespace:Hmisc'

I tried removing both the Hmisc and redcapAPI packages and reinstalling with dependencies = TRUE, but the problem persists.

**Comment by nutterb** [comment]
This is a side effect of the unfortunate-for-me decision for `Hmisc` to no longer export the label assignment and extraction functions.  I have most issues fixed already, but I have one more thing to do before I submit an update tomorrow.

If you need to use `redcapAPI` in the meantime, you will need to install `Hmisc` 4.0-2. (https://cran.r-project.org/src/contrib/Archive/Hmisc/)

You might also try `devtools::install_github("nutterb/redcapAPI", ref = "Version2")`.  It seems to work for exporting records, but there's a bug in exporting results I still need to fix before I submit this to CRAN.  I'll have the fix up before the 21st.

**Comment by nutterb** [comment]
Updated version is now on CRAN.
