### ISSUE TITLE
exportRecords() factors argument not working for one project, does work for others 

### ISSUE THREAD

**Issue by afrye3** [nutterb/redcapAPI#98]
The exportRecords() function for a single REDCap project only exports categorical data as numeric codes rather than labeled factors, regardless if factors argument is set to True or False. 

For other projects, data can be exported correctly. 

What might be causing this error/discrepancy?

Thanks!

**Comment by nutterb** [comment]
A couple things to consider:

1. Have you updated to the most recent version (`redcapAPI` 2.0). It went to CRAN yesterday (or Wednesday, I can't remember which).
2. Have you observed this difference in behavior today? Specifically, have you exported records from different projects today and observed these results? (This is to rule out the possibility that you see one behavior prior to the update and a different behavior after)

**Comment by afrye3** [comment]
I was working out of the previous version. (didn't know about the update!) I will try again once I have the update installed and if I encounter the same error, I may have more questions.

Thanks!

**Comment by nutterb** [comment]
@afrye3 just wanted to follow up on this.  Are you still seeing this problem?

**Comment by afrye3** [comment]
@nutterb, thanks for the follow-up. Unfortunately due to some IT problems out of my control, I have not been able to update the package yet and have had to revert to old techniques of interfacing with REDCap. If I'm ever able to test it, I will reach out again.
